services:
  # 1. Сервис нейросети (Ollama)
  ollama:
    build:
      context: ./ollama
    entrypoint: /bin/sh -c "ollama serve & (sleep 5 && ollama pull llama3:8b) & wait"
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"

  # 2. Сервис бэкенда
  backend:
    build:
      context: ./alfacreator-backend
    ports:
      - "8000:8000"
    depends_on:
      - ollama
    environment:
      - OLLAMA_HOST=http://ollama:11434
    volumes:
      - ./database_data:/app/database_data
      - ./alfacreator-backend/chroma_db:/app/chroma_db


  # 3. Сервис фронтенда
  frontend:
    build:
      context: ./alfacreator-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  ollama_data:
